name: Playwright Tests

permissions:
  contents: write

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 10 * * 1-5" # 6:00 AM ET Monday-Friday
    - cron: "0 17 * * 1-5" # 1:00 PM ET Monday-Friday
    - cron: "0 2 * * 2-6" # 10:00 PM ET (previous day) Monday-Friday
    - cron: "0 4 * * 0" # 12:00 AM ET Sunday

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          # Install UI dependencies
          npm install react react-dom @emotion/react framer-motion recharts @headlessui/react @heroicons/react tailwindcss postcss autoprefixer
          # Install test dependencies
          npm install -D @playwright/test
          npm install exceljs

      - name: Install only Chromium browser
        run: npx playwright install chromium --with-deps

      - name: Run Playwright test for applyJobs.spec.js
        run: npx playwright test tests/applyJobs.spec.js
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/

      - name: Upload Logs and Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: application-logs
          path: |
            Logs/
            Reports/

      - name: Get Date and Time
        id: get_date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "time=$(date +'%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Commit and push Logs and Reports
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Logs/ Reports/
          git commit -m "Add test Logs and Reports [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
